on:
  push:
    branches:
    - master
    - test
    - dev
  pull_request:
    branches:
    - master
    - test
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build Refit.sln --configuration Release
    # - name: Test
    #   run: dotnet test Refit.sln --configuration Release --no-build
