on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
env:
  PROJECT_DIR: "Refit"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/master
      run: git branch --remote --contains | grep origin/master
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-prerelease\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build Refit/Refit.csproj --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test Refit/Refit.csproj --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack Refit/Refit.csproj -p:PackageID=CCM.Refit --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Add Sources
      run: dotnet nuget add source --username ccm-engineering --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ccm-engineering/index.json"
    - name: Push
      run: dotnet nuget push $PROJECT_DIR/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
